// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Disease is the predicate function for disease builders.
type Disease func(*sql.Selector)

// Employee is the predicate function for employee builders.
type Employee func(*sql.Selector)

// Gender is the predicate function for gender builders.
type Gender func(*sql.Selector)

// MedicalCare is the predicate function for medicalcare builders.
type MedicalCare func(*sql.Selector)

// Patient is the predicate function for patient builders.
type Patient func(*sql.Selector)
