// Code generated by entc, DO NOT EDIT.

package medicalcare

import (
	"github.com/TP/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.MedicalCare {
	return predicate.MedicalCare(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MedicalCare {
	return predicate.MedicalCare(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MedicalCare {
	return predicate.MedicalCare(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MedicalCare {
	return predicate.MedicalCare(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MedicalCare {
	return predicate.MedicalCare(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MedicalCare {
	return predicate.MedicalCare(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MedicalCare {
	return predicate.MedicalCare(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MedicalCare {
	return predicate.MedicalCare(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MedicalCare {
	return predicate.MedicalCare(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// MedicalcareName applies equality check predicate on the "medicalcare_name" field. It's identical to MedicalcareNameEQ.
func MedicalcareName(v string) predicate.MedicalCare {
	return predicate.MedicalCare(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldMedicalcareName), v))
	})
}

// MedicalcareNameEQ applies the EQ predicate on the "medicalcare_name" field.
func MedicalcareNameEQ(v string) predicate.MedicalCare {
	return predicate.MedicalCare(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldMedicalcareName), v))
	})
}

// MedicalcareNameNEQ applies the NEQ predicate on the "medicalcare_name" field.
func MedicalcareNameNEQ(v string) predicate.MedicalCare {
	return predicate.MedicalCare(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldMedicalcareName), v))
	})
}

// MedicalcareNameIn applies the In predicate on the "medicalcare_name" field.
func MedicalcareNameIn(vs ...string) predicate.MedicalCare {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MedicalCare(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldMedicalcareName), v...))
	})
}

// MedicalcareNameNotIn applies the NotIn predicate on the "medicalcare_name" field.
func MedicalcareNameNotIn(vs ...string) predicate.MedicalCare {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MedicalCare(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldMedicalcareName), v...))
	})
}

// MedicalcareNameGT applies the GT predicate on the "medicalcare_name" field.
func MedicalcareNameGT(v string) predicate.MedicalCare {
	return predicate.MedicalCare(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldMedicalcareName), v))
	})
}

// MedicalcareNameGTE applies the GTE predicate on the "medicalcare_name" field.
func MedicalcareNameGTE(v string) predicate.MedicalCare {
	return predicate.MedicalCare(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldMedicalcareName), v))
	})
}

// MedicalcareNameLT applies the LT predicate on the "medicalcare_name" field.
func MedicalcareNameLT(v string) predicate.MedicalCare {
	return predicate.MedicalCare(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldMedicalcareName), v))
	})
}

// MedicalcareNameLTE applies the LTE predicate on the "medicalcare_name" field.
func MedicalcareNameLTE(v string) predicate.MedicalCare {
	return predicate.MedicalCare(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldMedicalcareName), v))
	})
}

// MedicalcareNameContains applies the Contains predicate on the "medicalcare_name" field.
func MedicalcareNameContains(v string) predicate.MedicalCare {
	return predicate.MedicalCare(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldMedicalcareName), v))
	})
}

// MedicalcareNameHasPrefix applies the HasPrefix predicate on the "medicalcare_name" field.
func MedicalcareNameHasPrefix(v string) predicate.MedicalCare {
	return predicate.MedicalCare(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldMedicalcareName), v))
	})
}

// MedicalcareNameHasSuffix applies the HasSuffix predicate on the "medicalcare_name" field.
func MedicalcareNameHasSuffix(v string) predicate.MedicalCare {
	return predicate.MedicalCare(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldMedicalcareName), v))
	})
}

// MedicalcareNameEqualFold applies the EqualFold predicate on the "medicalcare_name" field.
func MedicalcareNameEqualFold(v string) predicate.MedicalCare {
	return predicate.MedicalCare(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldMedicalcareName), v))
	})
}

// MedicalcareNameContainsFold applies the ContainsFold predicate on the "medicalcare_name" field.
func MedicalcareNameContainsFold(v string) predicate.MedicalCare {
	return predicate.MedicalCare(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldMedicalcareName), v))
	})
}

// HasPatients applies the HasEdge predicate on the "patients" edge.
func HasPatients() predicate.MedicalCare {
	return predicate.MedicalCare(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PatientsTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PatientsTable, PatientsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPatientsWith applies the HasEdge predicate on the "patients" edge with a given conditions (other predicates).
func HasPatientsWith(preds ...predicate.Patient) predicate.MedicalCare {
	return predicate.MedicalCare(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PatientsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PatientsTable, PatientsColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.MedicalCare) predicate.MedicalCare {
	return predicate.MedicalCare(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.MedicalCare) predicate.MedicalCare {
	return predicate.MedicalCare(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MedicalCare) predicate.MedicalCare {
	return predicate.MedicalCare(func(s *sql.Selector) {
		p(s.Not())
	})
}
