/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntMedicalCareEdges,
    EntMedicalCareEdgesFromJSON,
    EntMedicalCareEdgesFromJSONTyped,
    EntMedicalCareEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntMedicalCare
 */
export interface EntMedicalCare {
    /**
     * 
     * @type {EntMedicalCareEdges}
     * @memberof EntMedicalCare
     */
    edges?: EntMedicalCareEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntMedicalCare
     */
    id?: number;
    /**
     * MedicalcareName holds the value of the "medicalcare_name" field.
     * @type {string}
     * @memberof EntMedicalCare
     */
    medicalcareName?: string;
}

export function EntMedicalCareFromJSON(json: any): EntMedicalCare {
    return EntMedicalCareFromJSONTyped(json, false);
}

export function EntMedicalCareFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntMedicalCare {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntMedicalCareEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'medicalcareName': !exists(json, 'medicalcare_name') ? undefined : json['medicalcare_name'],
    };
}

export function EntMedicalCareToJSON(value?: EntMedicalCare | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntMedicalCareEdgesToJSON(value.edges),
        'id': value.id,
        'medicalcare_name': value.medicalcareName,
    };
}


