/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntPatientEdges,
    EntPatientEdgesFromJSON,
    EntPatientEdgesFromJSONTyped,
    EntPatientEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPatient
 */
export interface EntPatient {
    /**
     * 
     * @type {EntPatientEdges}
     * @memberof EntPatient
     */
    edges?: EntPatientEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntPatient
     */
    id?: number;
    /**
     * PatientID holds the value of the "patient_ID" field.
     * @type {string}
     * @memberof EntPatient
     */
    patientID?: string;
    /**
     * PatientAddress holds the value of the "patient_address" field.
     * @type {string}
     * @memberof EntPatient
     */
    patientAddress?: string;
    /**
     * PatientAge holds the value of the "patient_age" field.
     * @type {number}
     * @memberof EntPatient
     */
    patientAge?: number;
    /**
     * PatientBirthday holds the value of the "patient_birthday" field.
     * @type {string}
     * @memberof EntPatient
     */
    patientBirthday?: string;
    /**
     * PatientCardID holds the value of the "patient_cardID" field.
     * @type {string}
     * @memberof EntPatient
     */
    patientCardID?: string;
    /**
     * PatientName holds the value of the "patient_name" field.
     * @type {string}
     * @memberof EntPatient
     */
    patientName?: string;
    /**
     * PatientTel holds the value of the "patient_tel" field.
     * @type {string}
     * @memberof EntPatient
     */
    patientTel?: string;
}

export function EntPatientFromJSON(json: any): EntPatient {
    return EntPatientFromJSONTyped(json, false);
}

export function EntPatientFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPatient {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntPatientEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'patientID': !exists(json, 'patient_ID') ? undefined : json['patient_ID'],
        'patientAddress': !exists(json, 'patient_address') ? undefined : json['patient_address'],
        'patientAge': !exists(json, 'patient_age') ? undefined : json['patient_age'],
        'patientBirthday': !exists(json, 'patient_birthday') ? undefined : json['patient_birthday'],
        'patientCardID': !exists(json, 'patient_cardID') ? undefined : json['patient_cardID'],
        'patientName': !exists(json, 'patient_name') ? undefined : json['patient_name'],
        'patientTel': !exists(json, 'patient_tel') ? undefined : json['patient_tel'],
    };
}

export function EntPatientToJSON(value?: EntPatient | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntPatientEdgesToJSON(value.edges),
        'id': value.id,
        'patient_ID': value.patientID,
        'patient_address': value.patientAddress,
        'patient_age': value.patientAge,
        'patient_birthday': value.patientBirthday,
        'patient_cardID': value.patientCardID,
        'patient_name': value.patientName,
        'patient_tel': value.patientTel,
    };
}


