// Code generated by entc, DO NOT EDIT.

package disease

const (
	// Label holds the string label denoting the disease type in the database.
	Label = "disease"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDiseaseName holds the string denoting the disease_name field in the database.
	FieldDiseaseName = "disease_name"

	// EdgePatients holds the string denoting the patients edge name in mutations.
	EdgePatients = "patients"

	// Table holds the table name of the disease in the database.
	Table = "diseases"
	// PatientsTable is the table the holds the patients relation/edge.
	PatientsTable = "patients"
	// PatientsInverseTable is the table name for the Patient entity.
	// It exists in this package in order to avoid circular dependency with the "patient" package.
	PatientsInverseTable = "patients"
	// PatientsColumn is the table column denoting the patients relation/edge.
	PatientsColumn = "disease_id"
)

// Columns holds all SQL columns for disease fields.
var Columns = []string{
	FieldID,
	FieldDiseaseName,
}

var (
	// DiseaseNameValidator is a validator for the "disease_name" field. It is called by the builders before save.
	DiseaseNameValidator func(string) error
)
